services:
  - type: web
    name: upi-fraud-detection-api
    env: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mainapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false
